INSERT INTO COURSE ("ID", "NAME", "DURATION") VALUES (1000, 'Spring Boot', 60  );
INSERT INTO COURSE ("ID", "NAME", "DURATION") VALUES (1001, 'Spring Cloud', 120  );
INSERT INTO COURSE ("ID", "NAME", "DURATION") VALUES (1002, 'Cloud Foundry', 600  );

